name: Production
run-name: Deploy to Production by ${{ github.triggering_actor }}
on:
  push:
    branches: [master]

jobs:
  lint-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup job
        id: setup-job
        uses: ./.github/actions/setup-job

      - name: Lint project files
        run: pnpm run lint
