name: Production
run-name: Deploy to Production by ${{ github.triggering_actor }}
on:
  push:
    branches: [master]

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'master' && github.head_ref != 'staging'
        run: |
          echo "ERROR: You can only merge to main from dev."
          exit 1

  lint-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup job
        id: setup-job
        uses: ./.github/actions/setup-job

      - name: Lint project files
        run: pnpm run lint
